{% render "_xpack-dev-tools/.github/workflows/copyright-liquid.yml" %}

{% assign platforms = platforms | split: "," %}

name: 'Build xPack {{packageConfig.longName}}'

on:
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        type: string
        default: 'current'
      xpm_version:
        description: 'The version of xpm to install'
        required: false
        type: string
        default: 'next'
      xpm_install_loglevel:
        description: 'Optional loglevel for xpm install'
        required: false
        default: 'info'
        type: choice
        options:
        - silent
        - warn
        - info
        - verbose
        - debug
        - trace
      xpm_install_options:
        description: 'Optional switches to pass to xpm install'
        required: false
        type: string
        default: ''

jobs:
{% for platform in platforms %}
{% if platform == "linux-x64" %}
  linux-x64-x:
    name: 'Linux x64 X - {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    container:
      image: ilegeul/ubuntu:amd64-18.04-xbb-v5.2.1
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Show environment'
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          lsb_release -sd
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

      - name: 'Build Linux x64 binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config linux-x64 --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %}
          xpm run build --config linux-x64

      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build/linux-x64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
{% for platform in platforms %}
{% if platform == "win32-x64" %}
  linux-x64-w:
    name: 'Linux x64 W - {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    container:
      image: ilegeul/ubuntu:amd64-18.04-xbb-v5.2.1
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Show environment'
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          lsb_release -sd
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

      - name: 'Build Windows x64 binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config win32-x64 --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %}
          xpm run build --config win32-x64

      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build/win32-x64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
{% for platform in platforms %}
{% if platform == "linux-arm" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm, xbbla32]
    container:
      image: ilegeul/ubuntu:arm32v7-18.04-xbb-v5.2.1
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Show environment'
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          lsb_release -sd
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

      - name: 'Build {{platform}} binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config {{platform}} --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets
          xpm run build --config {{platform}} -C build-assets

      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build-assets/build/{{platform}}/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
{% for platform in platforms %}
{% if platform == "linux-arm64" %}
 {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm64, xbbla]
    container:
      image: ilegeul/ubuntu:arm64v8-18.04-xbb-v5.2.1
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Show environment'
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          lsb_release -sd
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

      - name: 'Build Linux arm64 binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config {{platform}} --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets
          xpm run build --config {{platform}} -C build-assets

      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build-assets/build/{{platform}}/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
{% for platform in platforms %}
{% if platform == "darwin-x64" %}
  macos-x64:
    name: 'macOS Intel - {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 2880 # 2 days
{% if MACOS_INTEL_VERSION %}
    runs-on: [self-hosted, macos, intel, {{MACOS_INTEL_VERSION}}]
{% else %}
    runs-on: [self-hosted, macos, intel]
{% endif %}
    steps:
      - name: 'Show environment'
        run: |
          echo "pwd: $(pwd)"
          echo "whoami: $(whoami)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          sw_vers
          xcode-select --print-path
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || xcodebuild -version
          ls -l /Library/Developer/CommandLineTools/usr/include || true
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

{% for platform in platforms %}
{% case platform %}
{% when "darwin-x64" %}
      - name: 'Build macOS x64 binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config darwin-x64 --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %}
          xpm run build --config darwin-x64
{% endcase %}
{% endfor %}
      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build/darwin-x64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
{% for platform in platforms %}
{% if platform == "darwin-arm64" %}
  macos-arm64:
    name: 'macOS Arm - {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} build'
    timeout-minutes: 2880 # 2 days
{% if MACOS_ARM_VERSION %}
    runs-on: [self-hosted, macos, apple, {{MACOS_ARM_VERSION}}]
{% else %}
    runs-on: [self-hosted, macos, apple]
{% endif %}
    steps:
      - name: 'Show environment'
        run: |
          echo "pwd: $(pwd)"
          echo "whoami: $(whoami)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          uname -a
          sw_vers
          xcode-select --print-path
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || xcodebuild -version
          ls -l /Library/Developer/CommandLineTools/usr/include || true
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1 # v1 for old Git
        with:
          fetch-depth: 3

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: |
          npm install --location=global xpm@{% raw %}${{github.event.inputs.xpm_version}}{% endraw %}
          xpm --version

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %} -C build-assets

{% for platform in platforms %}
{% case platform %}
{% when "darwin-arm64" %}
      - name: 'Build macOS arm64 binaries'
        timeout-minutes: 1440
        run: |
          xpm install --config darwin-arm64 --loglevel {% raw %}${{github.event.inputs.xpm_install_loglevel}}{% endraw %} {% raw %}${{github.event.inputs.xpm_install_options}}{% endraw %}
          xpm run build --config darwin-arm64

{% endcase %}
{% endfor %}
      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: 'build/darwin-arm64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build-assets/build build-assets/build-$(date -u +%Y%m%d-%H%M%S)
{% break %}
{% endif %}
{% endfor %}
