{% render "_xpack-dev-tools/.github/workflows/copyright-liquid.yml" %}

{% assign platforms = platforms | split: "," %}

name: 'Deep clean xPack {{packageConfig.longName}}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

jobs:
{% for platform in platforms %}
{% if platform == "linux-x64" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}

{% for platform in platforms %}
{% if platform == "win32-x64" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}

{% for platform in platforms %}
{% if platform == "linux-arm" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm, xbbla32]

    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}

{% for platform in platforms %}
{% if platform == "linux-arm64" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm64, xbbla]
    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}

{% for platform in platforms %}
{% if platform == "darwin-x64" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
{% if MACOS_INTEL_VERSION %}
    runs-on: [self-hosted, macos, intel, {{MACOS_INTEL_VERSION}}]
{% else %}
    runs-on: [self-hosted, macos, intel]
{% endif %}
    steps:
      - name: 'Show environment'
        run: |
          uname -a
          sw_vers # lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}

{% for platform in platforms %}
{% if platform == "darwin-arm64" %}
  {{platform}}:
    name: '{{platform}} {{packageName}} {% raw %}${{github.event.inputs.version}}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
{% if MACOS_ARM_VERSION %}
    runs-on: [self-hosted, macos, apple, {{MACOS_ARM_VERSION}}]
{% else %}
    runs-on: [self-hosted, macos, apple]
{% endif %}
    steps:
      - name: 'Show environment'
        run: |
          uname -a
          sw_vers # lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: 'Clean working area' # Mandatory for self-hosted runners.
        run: |
          chmod -Rf a+w * || true
          rm -rf * .git*
{% break %}
{% endif %}
{% endfor %}
