{% render "_xpack-dev-tools/.github/workflows/copyright-liquid.yml" %}

{% assign platforms_array = platforms | split: "," %}

name: 'Publish the xPack {{packageConfig.descriptiveName}} release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'
      helper-git-ref:
        description: 'The helper branch, tag or SHA to checkout'
        required: false
        default: 'xpack-development'

jobs:
  create-release:
    name: 'Create the pre-release'
    runs-on: ubuntu-24.04

    steps:
      - name: 'Show environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      # https://github.com/actions/checkout
      - name: 'Checkout project'
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: 'Checkout helper {% raw %}${{github.event.inputs.helper-git-ref}}{% endraw %}'
        uses: actions/checkout@v4
        with:
          repository: xpack-dev-tools/xbb-helper-xpack
          path: build-assets/xpacks/@xpack-dev-tools/xbb-helper
          ref: {% raw %}${{github.event.inputs.helper-git-ref}}{% endraw %}
          fetch-depth: 3

      - name: 'Create body'
        run: |
          ls -lLA
          npm --prefix build-assets install -dd
          ./build-assets/node_modules/.bin/liquidjs --context '{ "releaseVersion": "{% raw %}${{github.event.inputs.version}}{% endraw %}" }' --template @build-assets/templates/body-github-release-liquid.md --output .github/workflows/body-github-release.md
          cat .github/workflows/body-github-release.md

      - name: 'Publish release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          bodyFile: '.github/workflows/body-github-release.md'
          commit: 'xpack-development'
          draft: true
          name: 'xPack {{packageConfig.descriptiveName}} v{% raw %}${{github.event.inputs.version}}{% endraw %}'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: false
          repo: '{{packageName}}-xpack'
          tag: 'v{% raw %}${{github.event.inputs.version}}{% endraw %}'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}

      - name: 'Gather artifacts'
        run: 'bash build-assets/xpacks/@xpack-dev-tools/xbb-helper/github-actions/download-all-binaries.sh'

      - name: 'Publish artifacts'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifacts: '~/Downloads/xpack-binaries/{{packageName}}/*'
          commit: 'xpack-development'
          draft: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: false
          repo: '{{packageName}}-xpack'
          tag: 'v{% raw %}${{github.event.inputs.version}}{% endraw %}'
          token: {% raw %}${{secrets.PUBLISH_TOKEN}}{% endraw %}
